services:
  - type: web
    name: HawsaAI
    env: python
    repo: https://github.com/ hawsa1 / HawsaAI  # حط رابطك الصحيح
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python api_server.py"
    plan: free
